version: '3.1'
services:
  postgres-db:
    image: postgres
    container_name: postgres-local-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root1234
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

